### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'value')

### ISSUE THREAD

**Issue by forgetso** [Brushfam/typechain-polkadot#100]
`unwrapRecursively` fails when a result type is `null`.

```
{
  value: Result { ok: Result { ok: null, err: undefined }, err: undefined }, // result type is `null` inside 
  gasConsumed: Type(2) [Map] {
    'refTime' => Type {
      registry: [TypeRegistry],
      __internal__Type: [Function: u64],
      initialU8aLength: 5,
      __internal__raw: <BN: e198e0a5>
    },
    'proofSize' => Type {
      registry: [TypeRegistry],
      __internal__Type: [Function: u64],
      initialU8aLength: 4,
      __internal__raw: <BN: 10801>
    },

```

**Comment by varex83** [comment]
Hello @forgetso, thank you for reporting the issue! Can you provide some examples in order to speed up the process? 

Also, our team is a little bit busy right now with the new OpenBrush release, so it could take a little bit more time, thank you for understanding

**Comment by forgetso** [comment]
I was getting confused as querying a transaction does not have a `.value` field. The query result of a tx is simply `null`. Thx

**Comment by varex83** [comment]
No problem, Chris 👌 

Have a nice day! 💯
