### ISSUE TITLE
`OUTPUT_IS_NULL` error needs better description

### ISSUE THREAD

**Issue by Maar-io** [Brushfam/typechain-polkadot#54]
When call to runtime fails and there is no output
https://github.com/Brushfam/typechain-polkadot/blob/2dace24cecfe9a058354f27a41546937505e1545/packages/typechain-types/dist/src/query.js#L201-L204
there will be a `OUTPUT _IS_NULL `error like this:
```
Batch calls test
       DryRun for errors works:
     Error: the object {
  "issue": "OUTPUT_IS_NULL"
} was thrown, throw an Error :)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)

```
That is very hard to debug and you have no idea where it failed in the test. Some sort of better naming would be much appreciated.
`result.asErr.registry.findMetaError(result.asErr.asModule).method` will give exact error returned from the Runtime and will be very helpful in debugging.

**Comment by varex83** [comment]
Hello @Maar-io, sorry for this kind of issue, we will look into it the next week!

**Comment by forgetso** [comment]
Maybe the output being null is ok. You don't necessarily need to throw an error. Just return null and let the user handle the outcome.

**Comment by forgetso** [comment]
If I'm querying a `Mapping` for a key that doesn't exist in a contract, I would expect `null` to be returned.

**Comment by varex83** [comment]
Hello @Maar-io, do you have any examples of how to reproduce this problem, because in new releases of ink and cargo-contract this error shouldn't appear, would be grateful if you will provide me with some ABI or something like that

**Comment by forgetso** [comment]
Hey @varex83, I get this error when querying a function that returns nothing, e.g.

```rust
        #[ink(message)]
        #[ink(payable)]
        pub fn register(
            &mut self,
            url: Vec<u8>,

        ) -> Result<(), Error> {

            self.configure(Some(url))
        }
```

```TypeScript
    try {
        const queryResult = await tasks.contract.query.register(...registerArgs)
    } catch (err) {
        if (typeof err === 'object' && 'issue' in err && err.issue === 'OUTPUT_IS_NULL') {
             //ignore it...
```

**Comment by forgetso** [comment]
It's working. Thanks!
