### ISSUE TITLE
Make nativeAPI and nativeContract accessible

### ISSUE THREAD

**Issue by forgetso** [Brushfam/typechain-polkadot#71]
Great job on this package.

There are many things I would like to do with the existing api and contract on your generated classes but I can't because

```
TS2341: Property 'nativeContract' is private and only accessible within class 'Contract'.
```
This is unnecessarily restrictive and means I have to create a duplicate api and contract in my wrapper class.

**Comment by varex83** [comment]
@forgetso thank you for your feedback, will be done on Monday! Feel free to share your ideas with us, we can add them to the typechain functionality!
